#!/bin/bash

xrandr --dpi 192
xrdb -merge ~/.Xdefaults
xrdb -merge ~/.Xresources
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
~/bin/autorotate_screen.sh &

ydotoold &
touchegg &

picom &
1password --silent &
# udiskie -t &
parcellite &
#xiccd &
# arch-update --tray &

# eval $(gnome-keyring-daemon --start)
# export SSH_AUTH_SOCK


unclutter --idle 0 --root --hide-on-touch &

fc-cache -fv &

exec /usr/bin/awesome -a >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
