#!/bin/bash

xrandr --dpi 192
xrdb -merge ~/.Xdefaults
xrdb -merge ~/.Xresources
~/bin/autorotate_screen.sh &

ydotoold &
touchegg &

picom &
1password --silent &
# udiskie -t &
parcellite &
#xiccd &
# arch-update --tray &

# eval $(gnome-keyring-daemon --start)
# export SSH_AUTH_SOCK

fc-cache -fv &

exec /usr/bin/awesome -a >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
