#!/bin/bash
# TODO: move to dotfiles
#/usr/bin/prime-offload &
if [[ ! "$GIMPY_NVIDIA_MODE" = "" ]]; then
    xrandr --setprovideroutputsource modesetting NVIDIA-0
    xrandr --auto
fi
#xrandr --dpi 192

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [[ -f $sysresources ]]; then
    xrdb -merge $sysresources

fi

if [[ -f $sysmodmap ]]; then
    xmodmap $sysmodmap
fi

if [[ -f "$userresources" ]]; then
    xrdb -merge "$userresources"
fi

if [[ -f "$usermodmap" ]]; then
    xmodmap "$usermodmap"
fi

if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [[ -x "$f" ]] && . "$f"
 done
 unset f
fi

xrdb -merge ~/.Xresources &
xrdb -merge ~/.Xdefaults &

if [[ "$GIMPY_EMPTY_WM" == "1" ]]; then
    exec sleep infinity
    exit 0
fi

if [[ "$GIMPY_STREAMING_WM" == "1" ]]; then
    ( sleep 3; systemctl start --user sunshine ) &
    exec urxvt
    exit 0
fi

if [[ "$GIMPY_NO_STARTUP" != "1" ]]; then
    if [[ "$GIMPY_REDSHIFT" == "1" ]]; then
        redshift &
    fi

    1password --silent &
    udiskie -t &
    parcellite &
    arch-update --tray &
    xhidecursor &
    fc-cache -fv &

    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

#supergfxctl -m Hybrid &

exec /usr/bin/awesome -a >> ~/.cache/awesome/"stdout-display${DISPLAY}" 2>> ~/.cache/awesome/"stderr-display${DISPLAY}"

# vim: ft=bash
